"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import Time_t

import Odometry_t

class IndexedOdometry_t(object):
    __slots__ = ["stamp", "frame_id", "drone_id", "odom"]

    __typenames__ = ["Time_t", "int32_t", "int32_t", "Odometry_t"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.stamp = Time_t()
        self.frame_id = 0
        self.drone_id = 0
        self.odom = Odometry_t()

    def encode(self):
        buf = BytesIO()
        buf.write(IndexedOdometry_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.stamp._get_packed_fingerprint() == Time_t._get_packed_fingerprint()
        self.stamp._encode_one(buf)
        buf.write(struct.pack(">ii", self.frame_id, self.drone_id))
        assert self.odom._get_packed_fingerprint() == Odometry_t._get_packed_fingerprint()
        self.odom._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != IndexedOdometry_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return IndexedOdometry_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = IndexedOdometry_t()
        self.stamp = Time_t._decode_one(buf)
        self.frame_id, self.drone_id = struct.unpack(">ii", buf.read(8))
        self.odom = Odometry_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if IndexedOdometry_t in parents: return 0
        newparents = parents + [IndexedOdometry_t]
        tmphash = (0xc4af9b3f24689e4a+ Time_t._get_hash_recursive(newparents)+ Odometry_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if IndexedOdometry_t._packed_fingerprint is None:
            IndexedOdometry_t._packed_fingerprint = struct.pack(">Q", IndexedOdometry_t._get_hash_recursive([]))
        return IndexedOdometry_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

