"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class PointField_t(object):
    __slots__ = ["name", "offset", "datatype", "count"]

    __typenames__ = ["string", "int32_t", "int8_t", "int32_t"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.name = ""
        self.offset = 0
        self.datatype = 0
        self.count = 0

    def encode(self):
        buf = BytesIO()
        buf.write(PointField_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ibi", self.offset, self.datatype, self.count))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PointField_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PointField_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = PointField_t()
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.offset, self.datatype, self.count = struct.unpack(">ibi", buf.read(9))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if PointField_t in parents: return 0
        tmphash = (0xd92708412f05a3b6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if PointField_t._packed_fingerprint is None:
            PointField_t._packed_fingerprint = struct.pack(">Q", PointField_t._get_hash_recursive([]))
        return PointField_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

